FrostyX/tracer

tracer/resources/processes.py
https://github.com/FrostyX/tracer/issues/26
=> self.cmdline is method, not `list`

requirements.txt, tracer.spec, tracer/controllers/resource.py, tracer/resources/processes.py, tracer/resources/tracer.py
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> more psutil 2.x

tracer/packageManagers/rpm.py
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> rpm-python  instead rpm -ql

README.md, doc/source/get-tracer.rst, setup.py, tests/test_alpm.py, tracer/controllers/resource.py, tracer/packageManagers/alpm.py, tracer/resources/applications.py, tracer/resources/system.py, tracer/views/resource/applications.py
(Sorry for the un-related commits they were just trivial problems)
=> Add initial support for Archlinux

tracer/resources/applications.py
I'm not sure why dist check was there in the first place but other dist's uses systemd so lets make it for for them :-)
This was added in #53
=> if systemd is running then use systemctl

tracer.spec
Fixes https://bodhi.fedoraproject.org/updates/tracer-0.6.12-1.fc25#comment-518717
=> pythonX-tracer now requires tracer-common

requirements.txt
This gets the travis build passing
=> Find the right lxml version for py 3.4

Vagrantfile, tracer.spec
I ran into some other weird problems with F31, so use F30 for now
=> Update Vagrantfile to use Fedora 30

tracer/resources/processes.py
This PR introduces two changes when analyzing process arguments:
- Check if the argument is an absolute path. This avoids unnecessary system calls that look like this:
```
15160 15:09:27.340215 stat("--no-daemon", 0x7ffec78c75f0) = -1 ENOENT (No such file or directory) <0.000012>
15160 15:09:27.376073 stat("--keep-baud", 0x7ffec78c75f0) = -1 ENOENT (No such file or directory) <0.000012>
15160 15:09:27.380001 stat("--noclear", 0x7ffec78c75f0) = -1 ENOENT (No such file or directory) <0.000013>
```
- If the argument is an absolute path, use a subprocess which we can kill if it is long-running (1/2 second) to check if the argument is actually a file. This protects against indefinite hangups if the argument is on an NFS which is no longer reachable.
**To test with Forklift:**
- spin up a …
=> Use subprocess to check process path arguments

tests/test_applications.py, tests/test_tracer.py, tests/test_views.py, tracer.spec
https://copr.fedorainfracloud.org/coprs/frostyx/tracer/build/1403187/
=> Stub dbus calls in tests

tests/test_collections.py, tracer/packageManagers/rpm.py, tracer/resources/collections.py
More precisely these
- AttributeError: 'str' object has no attribute 'decode'
- TypeError: update() takes 2 positional arguments but 3 were given
=> Fixing some of the unicode and API errors

tests/test_applications.py, tracer/resources/applications.py
=> When there is no helper, it doesn't contain anything

tests/test_processes.py, tracer/resources/processes.py
=> Fix list index out of range for ssh process names

doc/source/user-guide.rst, po/cs.po, po/tracer.pot, tests/test_views.py, tracer/views/note_for_hidden.py
It seems there is a lot of changes but that's just because I regenerated *.pot and *.po files. Except for that, the change is really small.
PTAL @garrett
=> Improve phrasing of additional process text

doc/source/manpage.rst
=> Document exit codes in the man page

.travis.yml, Makefile, tests/test_applications.py, tests/test_package.py, tests/test_rules.py, tests/test_views.py, tracer.spec
Also, update some deprecated assertion calls.
=> Drop nosetests dependency, use pytest instead

data/applications.xml
=> Ignore sudo and su in the output

tests/test_views.py, tracer/resources/collections.py, tracer/views/default.py
=> Remove duplicates in suggested helpers

README.md, doc/source/get-tracer.rst
Additionally, I have reformatted the source of README.md, it was unreadable.
=> Add installation instructions for EPEL8

tracer/hooks.py, tracer/resources/pycomp.py
=> Use importlib instead of deprecated imp

tracer/packageManagers/dnf.py
=> More reliable check if /usr/lib/sysimage/dnf/ database should be used

tracer/main.py
=> Don't hang forever when executed via SSH

tracer.spec, tracer/packageManagers/dnf.py, tracer/resources/system.py
=> Implement support for DNF5

tracer/controllers/default.py
=> Add list of applications triggering reboot-required
