tests/__meta__.py
tracer/resources/system.py

The distribution name check function in Python is somewhat unreliable. For example, in Mageia, it will return `mandrake` instead of `mageia`. Not only that, `platform.linux_distribution()` is deprecated in Python 3.5 in favor of reading `/etc/os-release` anyway.
This pull request alters the distro name retrieval behavior to try to check for `/etc/os-release`, and if it exists, parse the file and return the `ID` value.

Change distro name retrieval to try to read /etc/os-release first

---

tests/test_dnf.py
tracer/packageManagers/dnf.py
tracer/packageManagers/rpm.py

Mageia support in tracer was incomplete, and bombed out with fun errors like:
```
[root@mgacauldron-dnftst yum.repos.d]# tracer
Traceback (most recent call last):
File "/usr/bin/tracer", line 34, in <module>
tracer.main.run()
File "/usr/lib/python2.7/site-packages/tracer/main.py", line 42, in run
return router.dispatch()
File "/usr/lib/python2.7/site-packages/tracer/resources/router.py", line 55, in dispatch
controller = DefaultController(self.args, self.packages)
File "/usr/lib/python2.7/site-packages/tracer/controllers/default.py", line 50, in __init__
System.package_manager(erased=args.erased),
File "/usr/lib/python2.7/site-packages/tracer/resources/system.py", line 76, in package_manager
return PackageManager(*map(get_instance, managers[distro]))
File …
```

Add support for Mageia in packageManagers & tests

---

tracer/packageManagers/rpm.py
tracer/packageManagers/yum.py
tracer/resources/system.py

We can add RHEL support by simply replicating everything that says "centos" using "rhel".
Fixes issue #57

Add RHEL support

---

data/applications.xml

```
[root@centos7-katello-client tracer]# tracer -e
You should restart:
* Some applications using:
sudo systemctl restart sshd
sudo systemctl restart tuned
* These applications manually:
dhclient
master
pickup
python
qmgr
[root@centos7-katello-client tracer]# systemctl restart NetworkManager
[root@centos7-katello-client tracer]# tracer -e
You should restart:
* Some applications using:
sudo systemctl restart sshd
sudo systemctl restart tuned
* These applications manually:
master
pickup
python
qmgr
[root@centos7-katello-client tracer]#
```

dhclient can be restarted via NetworkManager

---

tests/test_tracer.py
tracer/resources/applications.py
tracer/resources/processes.py

This ensure all processes with a TTY are 'SESSION' type. We also match ssh sessions against a regex as they don't have a TTY but should be 'SESSION' type.

Fixes #68 - recognised SSH sessions correctly

---

data/applications.xml

This issue is similar to #76.
Tested the restarting of the udisksd and upowerd daemon on CentOS 7:

Fix daemon configuration for udisksd and upowerd

---

setup.py

Importing `tracer.version` in the setup.py file yields the
evaluation of `tracer/__init__.py` - which ultimately leads to
the importing of psutil/beautifulsoup4.
Thus, a `pip install .` fails on a minimal system (that doesn't
already have those packages installed). For example when you are
in a Python virtual environment.
Note: if you want to test tracer in a virtual env you also have
to make the system's rpm package available (e.g. via linking
/usr/lib64/python2.7/site-packages/rpm to the virtual
site-packages directory).

Eliminate psutil/beautifulsoup4 dependencies

---

tracer/packageManagers/dpkg.py
tracer/resources/system.py

This uses `ID_LIKE`  in /etc/os-release to match against the list of hard coded OSs we already support.
https://www.freedesktop.org/software/systemd/man/os-release.html#ID_LIKE=
Hopefully it would allow for a much more supported distros  👍 
For example this makes it not necessary to explicitly list `ubuntu` anymore, as Ubuntu has `ID_LIKE=debain`.

Use ID_LIKE in /etc/os-release

---

tracer/resources/tracer.py

This compares `uname -r` to the directories in /lib/modules/, if a directory name in /lib/modules/ is bigger than `uname -r` a fake AffectedApplication is added for it.

Fixes - #45 Report reboot for new kernels

---

tracer.spec

There seems to be a problem that on F27 (maybe also others) python3-tracer transitively depends on python2-argparse.
See the issue description on [RhBug: 1492078](https://bugzilla.redhat.com/show_bug.cgi?id=1492078)
I think, that this is a solution for it.
@sean797, you wrote the particular condition in spec, do you agree with this PR, or am I missing something?

Fix argparse logic in spec

---

tracer/resources/processes.py

When privilege separation is enabled, sshd sessions produce two processes: a privileged parent process with root permissions and a restricted child process. This fixes processing of the privileged parent process.
Fixes #95.

Handle sshd sessions that use privilege separation

---

.travis.yml

Current versions of dbus-python [have a requirement on dbus >= 1.8][dbus], which isn't met on Ubuntu Trusty. This shouldn't be an issue when deployed, as the version of dbus-python in use will be whatever is provided by the distro.
Additionally, this removes testing on Python 3.3, which has been end-of-lifed, and adds testing on Python 3.7.
[dbus]: https://cgit.freedesktop.org/dbus/dbus-python/commit/?id=05ef07b9b5a6ae4b53dc80728563d2455fe7e24f

Test in Ubuntu Xenial images with current Python

---

tracer/packageManagers/dnf.py
tracer/packageManagers/rpm.py

This will fail again if the schema changes substantially again.
It might be a good idea to investigate using the Python YUM/DNF libraries to get this information. Additionally, if a new version of DNF is or was at one point installed, but either YUM or an old version of DNF has since been used, transactions made by YUM or old DNF will not be captured. This shouldn't affect most systems, but could affect CentOS 7 systems on which [YUM 4] has been installed and then either removed or ignored in favor of the system YUM.
Fixes #116.
[YUM 4]: https://blog.centos.org/2017/10/yum-4-is-available-for-testing/

Support current versions of DNF

---

tracer/resources/processes.py

`Process.terminal()` returns the path to the terminal attached to the process, if one exists. This will include most processes launched interactively, not just processes that represent sessions. This implements a new heuristic, in which a process is a session if it has a terminal attached and either somehow has no parent or its parent has a different terminal attached. This heuristic is probably not foolproof, but should be sufficient for the majority of cases.
Fixes #119.

Improve session detection logic

---

tracer/resources/tracer.py

This prevents a false positive in `_has_updated_kernel` when a newer kernel-debug package is installed compared to the running kernel. Now it will return False
```
[root@rhel7 tracer]# rpm -q kernel
kernel-3.10.0-1062.el7.x86_64
[root@rhel7 tracer]# ll /lib/modules/
total 8
drwxr-xr-x. 7 root root 4096 Mar 26 16:45 3.10.0-1062.18.1.el7.x86_64.debug
drwxr-xr-x. 7 root root 4096 Aug  8  2019 3.10.0-1062.el7.x86_64
[root@rhel7 tracer]# tracer -a
```
Bugzilla report: https://bugzilla.redhat.com/show_bug.cgi?id=1709842

Ignore debug kernels when checking if kernel has been updated

---

tracer/packageManagers/ipackageManager.py
tracer/packageManagers/rpm.py
tracer/resources/PackageManager.py
tracer/resources/package.py
tracer/resources/system.py
tracer/resources/tracer.py

There are cases when uninstalling a kernel will leave files behind in /lib/modules resulting in a false positive for `_has_updated_kernel`. This PR changes that method to rely on the system's package data to determine the latest installed version and compare the running kernel to it.
Turns out this is actually quite complex. To truly make a comparison on an RPM system we need to look at the package EVR closely. I don't have the capacity to update the other package managers - and I'd say they weren't truly working anyway with the old approach - so no difference there. I've attempted to organize the code in a way that makes it easy to extend functionality to the other distros.

Use package manager to determine latest kernel

---

tracer/controllers/default.py
tracer/packageManagers/dnf.py
tracer/resources/system.py

Traces were not being reported accurately because the transaction DB wasn't getting found due to using the Yum package manager.
This also fixes an issue with the --user flag so it can take both `*` and `"*"` to avoid confusion

Use DNF on RHEL

---

tests/test_applications.py
tests/test_rules.py
tests/test_tracer.py
tracer.spec
tracer/resources/applications.py
tracer/resources/rules.py

Beautiful Soup package is not available on all systems (e.g. RHEL 8)
which complicates porting Tracer to such distributions. At the same
time, we don't really need any special feature from bs4 that built-in
`xml.dom.minidom` implementation doesn't provide as well.
I am also adding (and fixing) some tests to make sure the XML parsing
worked, and still works, as expected.

Drop beautifulsoup4 in favor of built-in xml.dom

---

tracer.spec
tracer/resources/processes.py

The `python3-future` package is not available in RHEL 8, and the
`python3-six` is a recommended way of importing `with_metaclass` anyway.
I spent a couple of hours debugging this thinking that there is
somemething wrong with `__future__` which is not the issue at all.

Depend on python3-six instead of python3-future

---

tracer/main.py
tracer/resources/applications.py
tracer/resources/exceptions.py
tracer/resources/rules.py

We can define custom applications and rules for example in
`~/.config/tracer/applications.xml` and `~/.config/tracer/rules.xml`.
When there is an syntax error, we want to print something like
Unable to parse /home/jkadlcik/.config/tracer/rules.xml
Hint: not well-formed (invalid token): line 4, column 0
Instead of
File "/usr/lib64/python3.9/xml/dom/minidom.py", line 1998, in parseString
return expatbuilder.parseString(string)
File "/usr/lib64/python3.9/xml/dom/expatbuilder.py", line 925, in parseString
return builder.parseString(string)
File "/usr/lib64/python3.9/xml/dom/expatbuilder.py", line 223, in parseString
parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 4, column 0

Print a user-friendly error when a xml file cannot be parsed

---

tracer/packageManagers/dnf.py
tracer/resources/system.py

SUSE distributions are able to use the DNF package manager with tracer
through the plugin, so we should have support for it.
SUSE distributions also relocate the persistent state data from `/var/lib`
to `/usr/lib/sysimage` for the Btrfs system snapshot setup.

Add support for SUSE distributions using DNF

---

tracer.spec

We already `BuildRequires` it so everything builds successfully but
execution on EPEL7 fails with the following error
[root@60d227f15636 /]# tracer
Traceback (most recent call last):
File "/usr/bin/tracer", line 33, in <module>
import tracer.main
File "/usr/lib/python2.7/site-packages/tracer/__init__.py", line 3, in <module>
from tracer.query import Query
File "/usr/lib/python2.7/site-packages/tracer/query.py", line 19, in <module>
from tracer.resources.tracer import Tracer
File "/usr/lib/python2.7/site-packages/tracer/resources/tracer.py", line 24, in <module>
from tracer.resources.system import System
File "/usr/lib/python2.7/site-packages/tracer/resources/system.py", line 31, in <module>
from tracer.resources.processes import Process
File …

Add missing runtime dependency on python2-six

---

tracer/packageManagers/dnf.py
tracer/packageManagers/rpm.py
tracer/packageManagers/yum.py
tracer/resources/system.py

Without this patch tracer always returns empty result as by default
`dnf` is being used on centos and not `yum`.

CentOS uses DNF

---

tracer/resources/applications.py

Fix #148 (hopefully)
I am not entirely sure about the cause of #148 but possibly processes
disappear between we check if there are any instances and accesing
them?
Let's try to access them just once.

Access process PID only once

---

tests/test_processes.py
tracer/resources/SystemdDbus.py

Fix #122
If we cannot find any unit/process with a given PID, simply return
`False` as for other unsuccessful cases.

Don't traceback for nonexisting PID

---

tests/test_collections.py
tracer/resources/collections.py

Fix #151
Fix #156
RHBZ 1958779
RHBZ 1940718
MGABZ 28577
I was trying to fix this issue several times already and the best
summary I could write was this one
https://github.com/FrostyX/tracer/issues/151#issuecomment-660066481
It doesn't any sense to me since the problematic line is
self.args.applications.with_helpers().exclude_types(types).sorted("helper")
which first filters only applications that have non-`None` helper and
only those try to sort, i.e. when sorting there shouldn't be any
`None` values.
Anyway, the issue is real and occurs to many people, so I am reworking
the sorting function and making sure it doesn't traceback when some
helper is `None`. I have no idea what are the problematic applications
and how they will be displayed in the output but I guess everything is
better …

Make sure Collection.sorted doesn't traceback for None values

---

Vagrantfile
doc/source/developer-guide.rst
requirements.txt
tracer.spec

In 9abc7eab6dd39146136 bs4 was dropped as dependency, but not from the
Vagrantfile and requirements.txt. lxml was used for HTML parsing with
bs4 and can also be dropped from requirements and packaging.

Drop beautifulsoup4/lxml dependencies

---

tracer/packageManagers/alpm.py

Implement a naive find_package for alpm which simply checks if the given
version corresponds to the installed package version.
This does not make the kernel version check work yet on Arch Linux, as the `kernel` package is hardcoded in code, but at least it does not make `tracer` throw a backtrace when running.

Add find_package support for alpm

---

requirements.txt
tests/__meta__.py
tracer.spec
tracer/resources/system.py

Fix #175
We also needed to rename all variables named `distro` to not shadow
the imported module name.

Use distro.id() instead of platform.linux_distribution()

---

tracer/resources/applications.py

Python interperts unicode escape sequences literally when used in a
normal string, it is generally recommended to use raw strings for regex
and this resolves the deprecation warning.

Fix Python DeprecationWarning: invalid escape sequence

---

tracer.spec

Fix #183
It was introduced in 15ad905 in order to compare version numbers,
however the code was reworked and we don't use it anymore.

Drop python-setuptools runtime dependency

---

tracer/controllers/default.py

`print_helper()` takes an application, not an application name, as its first argument, and expects that argument to have an attribute named `instances`:
https://github.com/FrostyX/tracer/blob/b390877a743ab9e7fd4857ed7bfcbf92d35c991c/tracer/controllers/helper.py#L45-L48
Clears up a traceback when running `tracer` with `--helpers`:
```text
$ sudo tracer -iat 1653306651.5944774 --helpers
Traceback (most recent call last):
File "/usr/bin/tracer", line 34, in <module>
tracer.main.run()
File "/usr/lib/python3.10/site-packages/tracer/main.py", line 51, in run
return router.dispatch()
File "/usr/lib/python3.10/site-packages/tracer/resources/router.py", line 54, in dispatch
controller.render_helpers()
File "/usr/lib/python3.10/site-packages/tracer/controllers/default.py", line 77, in …
```

Fix argument passed to print_helper()

---

tracer/controllers/default.py

Create /var/run/reboot-required file

---

tracer/packageManagers/rpm.py

Fix #198
Per `help(rpm.fi)`:
> DEPRECATED! This old API mixes storing and iterating over the meta data
> of the files of a package. Use rpm.files and rpm.file data types as a
> much cleaner API.
We could use
return [x.name for x in rpm.files(hdr)]
but this seems easier
return hdr[rpm.RPMTAG_FILENAMES]

Stop using deprecated rpm.fi

---

tracer/resources/tracer.py

File "/home/jkadlcik/git/tracer/tracer/resources/tracer.py", line 117, in trace_affected
if self._erased and not self._PACKAGE_MANAGER.provided_by(a.name):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/jkadlcik/git/tracer/tracer/resources/PackageManager.py", line 63, in provided_by
return self.package_managers[0].provided_by(app)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/jkadlcik/git/tracer/tracer/packageManagers/rpm.py", line 165, in provided_by
process = app.instances[0]  # @TODO Reimplement for all processes
^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'instances'

Fix traceback when tracer is called with --erased

---

tracer/packageManagers/dnf.py
tracer/packageManagers/rpm.py
tracer/resources/applications.py
tracer/resources/processes.py

Fix RHBZ 2094448
I couldn't reproduce the exact
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1745231  413.627    0.000  413.627    0.000 {method 'split' of '_sre.SRE_Pattern' objects}
9175435   35.478    0.000  473.426    0.000 /usr/lib/python3.6/site-packages/tracer/resources/processes.py:76(name)
```
from the mentioned RHBZ but I replaced the regex with simpler operations and also added some caching here and there to get a big performance boost.

Massive performance boost

---

README.md

needrestart is more featureful than tracer, but written in Perl.

Add needrestart to the similar software list
